source:
  host: ldap://10.2.1.1:8080
  port: 8080
  dn: cn=Directory Manager
  username: abc
  password: asbc
target:
  - host: ldap://10.2.1.1:8080
    dn: cn=Directory Manager
    port: 8080
    username: abc
    password: asbc
  - host: ldap://10.2.1.1:8081
    port: 8080
    dn: cn=Directory Manager
    username: abc
    password: asbc
period: 120
