serverPort: 8080
source:
  host: 10.7.6.79
  port: 1389
  dn: cn=Directory Manager
  username: cn=Directory Manager
  password: IDMtqls@2020
target:
  - host: 10.7.6.85
    dn: cn=Directory Manager
    port: 1389
    username: cn=Directory Manager
    password: IDMtqls@2020
#  - host: ldap://10.2.1.1:8081
#    port: 8080
#    dn: cn=Directory Manager
#    username: abc
#    password: asbc
period: 120
startEnable: false
